name: random_food
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # --- 2. Bản đồ (OpenStreetMap) ---
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  
  # --- 3. Tiện ích ---
  url_launcher: ^6.2.0        # Mở Google Maps
  flutter_fortune_wheel: ^1.2.0 # Vòng quay
  provider: ^6.1.1            # Quản lý trạng thái (Để dùng DB mọi nơi)
  http: ^1.1.0            # Để gửi yêu cầu tìm kiếm lên mạng
  flutter_typeahead: ^5.2.0 # Để hiện cái bảng gợi ý (Dropdown)
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^6.0.0
  # --- Tool sinh code cho Drift (Bắt buộc) ---
  build_runner: ^2.4.6
  drift_dev: ^2.13.0


flutter:


  uses-material-design: true

